/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SecretsRouteImport } from "./routes/secrets";
import { Route as PagesRouteImport } from "./routes/pages";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as FoldersRouteImport } from "./routes/folders";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";

const SignupRoute = SignupRouteImport.update({
	id: "/signup",
	path: "/signup",
	getParentRoute: () => rootRouteImport,
} as any);
const SecretsRoute = SecretsRouteImport.update({
	id: "/secrets",
	path: "/secrets",
	getParentRoute: () => rootRouteImport,
} as any);
const PagesRoute = PagesRouteImport.update({
	id: "/pages",
	path: "/pages",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const FoldersRoute = FoldersRouteImport.update({
	id: "/folders",
	path: "/folders",
	getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
	id: "/about",
	path: "/about",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/about": typeof AboutRoute;
	"/folders": typeof FoldersRoute;
	"/login": typeof LoginRoute;
	"/pages": typeof PagesRoute;
	"/secrets": typeof SecretsRoute;
	"/signup": typeof SignupRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/about": typeof AboutRoute;
	"/folders": typeof FoldersRoute;
	"/login": typeof LoginRoute;
	"/pages": typeof PagesRoute;
	"/secrets": typeof SecretsRoute;
	"/signup": typeof SignupRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/about": typeof AboutRoute;
	"/folders": typeof FoldersRoute;
	"/login": typeof LoginRoute;
	"/pages": typeof PagesRoute;
	"/secrets": typeof SecretsRoute;
	"/signup": typeof SignupRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/about"
		| "/folders"
		| "/login"
		| "/pages"
		| "/secrets"
		| "/signup";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/about"
		| "/folders"
		| "/login"
		| "/pages"
		| "/secrets"
		| "/signup";
	id:
		| "__root__"
		| "/"
		| "/about"
		| "/folders"
		| "/login"
		| "/pages"
		| "/secrets"
		| "/signup";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	AboutRoute: typeof AboutRoute;
	FoldersRoute: typeof FoldersRoute;
	LoginRoute: typeof LoginRoute;
	PagesRoute: typeof PagesRoute;
	SecretsRoute: typeof SecretsRoute;
	SignupRoute: typeof SignupRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/signup": {
			id: "/signup";
			path: "/signup";
			fullPath: "/signup";
			preLoaderRoute: typeof SignupRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/secrets": {
			id: "/secrets";
			path: "/secrets";
			fullPath: "/secrets";
			preLoaderRoute: typeof SecretsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/pages": {
			id: "/pages";
			path: "/pages";
			fullPath: "/pages";
			preLoaderRoute: typeof PagesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/folders": {
			id: "/folders";
			path: "/folders";
			fullPath: "/folders";
			preLoaderRoute: typeof FoldersRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/about": {
			id: "/about";
			path: "/about";
			fullPath: "/about";
			preLoaderRoute: typeof AboutRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AboutRoute: AboutRoute,
	FoldersRoute: FoldersRoute,
	LoginRoute: LoginRoute,
	PagesRoute: PagesRoute,
	SecretsRoute: SecretsRoute,
	SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
